FROM python:3.12.1-bookworm

RUN apt update; \
    apt install -y virtualenv fuse3 libfuse2

RUN echo "user_allow_other" >> /etc/fuse.conf


ARG USER=dev

RUN useradd -rm -d /home/${USER} -s /bin/bash -g root -G sudo -u 1000 ${USER}
USER ${USER}

WORKDIR /home/${USER}

COPY . ./

RUN pip install -r requirements.txt

CMD ["python", "mockarchiver.py"]