FROM python:3.12.1-bookworm

RUN apt update; \
    apt install -y virtualenv fuse3 libfuse2

RUN echo "user_allow_other" >> /etc/fuse.conf


RUN useradd -rm -d /home/mockarchiver -s /bin/bash -g root -G sudo -u 1000 mockarchiver
USER mockarchiver

WORKDIR /home/mockarchiver

COPY . ./

RUN pip install -r requirements.txt

CMD ["python", "mockarchiver.py"]