version: 2
updates:
  # Backend API – Python dependencies (managed with uv)
  - package-ecosystem: "pip"
    directory: "/backend/api"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    # uv uses a requirements.txt or a lock file; Dependabot works on the same files
    # Restrict updates to minor and patch releases (no major bumps)
    versioning-strategy: "increase"
    # Optional: automatically merge safe updates
    # automerge: true

  # Backend Archiver – Python dependencies (managed with uv)
  - package-ecosystem: "pip"
    directory: "/backend/archiver"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"