include:
  - infra.docker-compose.yml
  - minio.docker-compose.yml
  - jobs.docker-compose.yml
  - prefect-worker.docker-compose.yml
  # - monitoring.docker-compose.yml


networks:
  scopemarchiver_network:
    name: scopemarchiver_network
    driver: bridge
