services:
  prefect-config:
    image: ${PREFECT_CONFIG_IMAGE_NAME}:${OPENEM_IMAGE_TAG}
    container_name: prefect-config
    # profiles:
    #   - config
    #   - full
    build:
      context: ./backend/
      dockerfile: ./prefect-config.Dockerfile
      args:
        PREFECT_VERSION: ${PREFECT_VERSION}
    networks:
      - scopemarchiver_network
    environment:
      - PREFECT_LOGGING_LEVEL=${PREFECT_LOGGING_LEVEL}
      - PREFECT_API_URL=http://prefect-server:4200/api
      - SCICAT_ENDPOINT=${SCICAT_ENDPOINT}
      - MINIO_EXTERNAL_ENDPOINT=${HOST}:9000
      # Secrets are stored as blocks, removing _FILE suffix
      - MINIO_USER_FILE=/run/secrets/minio_user
      - MINIO_PASSWORD_FILE=/run/secrets/minio_pass
      - GITHUB_USER_FILE=/run/secrets/github_user
      - GITHUB_PASSWORD_FILE=/run/secrets/github_pass
      - SCICAT_USER_FILE=/run/secrets/scicat_user
      - SCICAT_PASSWORD_FILE=/run/secrets/scicat_pass
    volumes:
      - type: bind
        source: ./backend/prefect-vars.toml
        target: /var/local/prefect-vars.toml
      - type: bind
        source: ./backend/concurrency-limits.toml
        target: /var/local/concurrency-limits.toml
    command: "-v /var/local/prefect-vars.toml -s MINIO_USER_FILE MINIO_PASSWORD_FILE GITHUB_USER_FILE GITHUB_PASSWORD_FILE SCICAT_USER_FILE SCICAT_PASSWORD_FILE -l /var/local/concurrency-limits.toml"
    depends_on:
      prefect-server:
        condition: service_healthy
    secrets:
      - minio_user
      - minio_pass
      - github_user
      - github_pass
      - scicat_user
      - scicat_pass
  prefect-flows-deployment:
    image: prefecthq/prefect:${PREFECT_VERSION}
    container_name: prefect-flows-deployment
    # profiles:
    #   - full
    #   - config
    #   - deploy
    networks:
      - scopemarchiver_network
    environment:
      ### Prefect specific values
      - PREFECT_LOGGING_LEVEL=${PREFECT_LOGGING_LEVEL}
      - PREFECT_API_URL=http://prefect-server:4200/api
      - EXTRA_PIP_PACKAGES=prefect-docker==0.6.1
      ### Deployment values for interpolation in prefect.yaml
      - PREFECT_VERSION=${PREFECT_VERSION}
      - PREFECT_WORKER_LTS_VOLUME_NAME=scopemarchiver_${PREFECT_WORKER_LTS_VOLUME_NAME}
      - LTS_ROOT_FOLDER=${LTS_ROOT_FOLDER}
      - PREFECT_NETWORK=scopemarchiver_network
    command: prefect --no-prompt deploy --all --prefect-file /home/dev/backend/prefect.yaml
    working_dir: /home/dev/
    volumes:
      - type: bind
        source: ./
        target: /home/dev/
        read_only: true
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      prefect-server:
        condition: service_healthy
volumes:
  lts-mock-volume:
    driver: local
  nfs-lts-share:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=lts22,nolock"
      device: ":/scopem_lts_nfs_test_lts22"

secrets:
  github_user:
    file: ./.secrets/githubuser.txt
  github_pass:
    file: ./.secrets/githubpass.txt
  scicat_user:
    file: ./.secrets/scicatuser.txt
  scicat_pass:
    file: ./.secrets/scicatpass.txt
  minio_user:
    file: ./.secrets/miniouser.txt
  minio_pass:
    file: ./.secrets/miniopass.txt
