site_name: ScopeMArchiver
theme:
  name: "material"
  palette:
    primary: teal
  features:
    - toc.follow
    - toc.integrate
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [backend/archiver]
  - search  
  - gen-files:
      scripts:
      - ./docs/scripts/gen_ref_pages.py  
  - literate-nav:
      nav_file: referece/Summary.md
  - drawio
  - mermaid2
  - panzoom:
      mermaid: true
      full_screen: true
nav:
  - Introduction: index.md
  - Architecture: architecture.md
  - Deployment: deployment.md
  - Flows: 
      - Ingestion: upload_flow.md
      - Archival and Retrieval: archival_retrieval_flow.md
  - Code Reference: reference/
docs_dir: ./docs
site_dir: ./.site
site_url: http://0.0.0.0:8000
repo_url: https://github.com/SwissOpenEM/ScopeMArchiver
repo_name: SwissOpenEM/ScopeMArchiver

markdown_extensions:
  - markdown_include.include:
      base_path: docs