
[archiver]
ARCHIVER_SCRATCH_FOLDER = "/tmp/scratch"
ARCHIVER_TARGET_SIZE_MB = 200
ARCHIVER_LTS_FILE_TIMEOUT_S = 300


[lts]
LTS_STORAGE_ROOT = "/tmp/LTS"
LTS_FREE_SPACE_PERCENTAGE = 20

[minio]
MINIO_REGION = "eu-west-1"
MINIO_RETRIEVAL_BUCKET = "retrieval"
MINIO_LANDINGZONE_BUCKET = "landingzone"
MINIO_STAGING_BUCKET = "staging"
MINIO_ENDPOINT = "scopem-openemdata.ethz.ch:9090"

[scicat]
SCICAT_ENDPOINT = "http://scopem-openem.ethz.ch:89"
SCICAT_API_PREFIX = "/api/v3/"
