
[archiver]
ARCHIVER_SCRATCH_FOLDER = "/tmp/scratch" #string


[lts]
LTS_STORAGE_ROOT = "/tmp/LTS"  #string
LTS_FREE_SPACE_PERCENTAGE = 20

[api]
API_ROOT_PATH = '/api/v1'
API_PORT = 8000
API_LOG_LEVEL = "info"

[minio]
MINIO_REGION = "eu-west1"                # secret
MINIO_PASSWORD = "minioadmin"            #secret
MINIO_USER = "minioadmin"                # secret
MINIO_RETRIEVAL_BUCKET = "retrieval"     # string
MINIO_LANDINGZONE_BUCKET = "landingzone" # string
MINIO_STAGING_BUCKET = "staging"         #string
MINIO_ENDPOINT = "minio:9000"                 #string

[scicat]
SCICAT_ENDPOINT = "http://scicatmock:8000" # string
SCICAT_API_PREFIX = "/"                    # string
