
[archiver]
ARCHIVER_SCRATCH_FOLDER = "/tmp/scratch" #string
ARCHIVER_TARGET_SIZE_MB = 200

[lts]
LTS_STORAGE_ROOT = "/tmp/LTS"  #string
LTS_FREE_SPACE_PERCENTAGE = 20

[minio]
MINIO_REGION = "eu-west1"                # secret
MINIO_RETRIEVAL_BUCKET = "retrieval"     # string
MINIO_LANDINGZONE_BUCKET = "landingzone" # string
MINIO_STAGING_BUCKET = "staging"         #string
MINIO_ENDPOINT = "minio:9000"            #string

[scicat]

SCICAT_API_PREFIX = "/api/v3/" # string
