// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RemoveUpload(arg1) {
  return window['go']['main']['App']['RemoveUpload'](arg1);
}

export function ScheduleUpload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScheduleUpload'](arg1, arg2, arg3, arg4);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function Upload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Upload'](arg1, arg2, arg3, arg4);
}
