// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RemoveUpload(arg1:string):Promise<void>;

export function ScheduleUpload(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SelectFolder():Promise<void>;

export function Upload(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;
