// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelection():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function SelectFolder():Promise<Array<string>>;

export function Upload(arg1:string):Promise<string>;
