services:
  archiver-service-api:
    image: ${OPENEM_BACKEND_IMAGE_NAME}:${OPENEM_IMAGE_TAG}
    build:
      context: ../backend/api
      dockerfile: ./Dockerfile
    environment:
      - PREFECT_LOGGING_LEVEL=${PREFECT_LOGGING_LEVEL}
      - PREFECT_API_URL=http://prefect-server:4200/api
      - UVICORN_PORT=8000
      - UVICORN_LOG_LEVEL=info
      - UVICORN_RELOAD=False
      - S3_ENDPOINT=${S3_EXTERNAL_ENDPOINT}
      - IDP_URL=${IDP_URL}
      - IDP_USERNAME=${IDP_USERNAME}
      - IDP_REALM=${IDP_REALM}
      - IDP_AUDIENCE=${IDP_AUDIENCE}
      - IDP_CLIENT_ID=${IDP_CLIENT_ID}
      - SCICAT_INGESTOR_GROUPS=${SCICAT_INGESTOR_GROUPS}
      - S3_TOTAL_LANDING_SPACE_TB=${S3_TOTAL_LANDING_SPACE_TB}
    secrets:
      - s3_metrics_token
      - idp_client_secret
      - idp_password
      - job_endpoint_username 
      - job_endpoint_password
    expose:
      - 8000
    networks:
      - ${ENVIRONMENT}_traefik_public
      - internal
    privileged: false
    read_only: true
    labels:
      traefik.enable: true
      traefik.docker.network: ${ENVIRONMENT}_traefik_public

  prefect-server:
    image: prefecthq/prefect:${PREFECT_VERSION}
    restart: always
    volumes:
      - prefect-volume:/root/.prefect
    privileged: false
    entrypoint:
      - /bin/sh
      - -c
      - |
        export PREFECT_API_DATABASE_PASSWORD=$$(cat /var/run/secrets/postgres_pass)
        export PREFECT_API_DATABASE_USER=$$(cat /var/run/secrets/postgres_user)
        export PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://$$PREFECT_API_DATABASE_USER:$$PREFECT_API_DATABASE_PASSWORD@postgres:5432/prefect
        /opt/prefect/entrypoint.sh prefect server start
    networks:
      - ${ENVIRONMENT}_traefik_public
      - internal
    secrets:
      - postgres_pass
      - postgres_user
    healthcheck:
      test: ["CMD", "prefect", "version"]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 5s
    environment:
      - PREFECT_LOGGING_LEVEL=${PREFECT_LOGGING_LEVEL}
      - PREFECT_HOME=/opt/prefect
      - PREFECT_API_DATABASE_ECHO=False
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True
      - PREFECT_TASK_DEFAULT_RETRIES=2
      - PREFECT_TASK_DEFAULT_RETRY_DELAY_SECONDS=[1,10,100]
      # working; PREFECT has some issues with api prefixes...
      - PREFECT_UI_URL=http://prefect-server:4200/api
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_UI_SHOW_PROMOTIONAL_CONTENT=False
    expose:
      - 4200
    depends_on:
      - postgres
    labels:
      traefik.enable: true
      traefik.docker.network: ${ENVIRONMENT}_traefik_public
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pass
      - POSTGRES_DB=prefect
    secrets:
      - postgres_user
      - postgres_pass
    expose:
      - 5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - internal

  prefect-config:
    image: ${PREFECT_CONFIG_IMAGE_NAME}:${OPENEM_IMAGE_TAG:-latest}
    build:
      context: ../backend/
      dockerfile: ./prefect/config.Dockerfile
      args:
        PREFECT_VERSION: ${PREFECT_VERSION}
      tags:
        - ${OPENEM_IMAGE_TAG}
    networks:
      - internal
    environment:
      - PREFECT_LOGGING_LEVEL=${PREFECT_LOGGING_LEVEL}
      - PREFECT_API_URL=http://prefect-server:4200/api
      - SCICAT_ENDPOINT=${SCICAT_ENDPOINT}
      - S3_EXTERNAL_ENDPOINT=${S3_EXTERNAL_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      # Secrets are stored as blocks, removing _FILE suffix
      - S3_USER_FILE=/run/secrets/s3_user
      - S3_PASSWORD_FILE=/run/secrets/s3_password
      - GITHUB_USER_FILE=/run/secrets/github_user
      - GITHUB_PASSWORD_FILE=/run/secrets/github_pass
      - SCICAT_USER_FILE=/run/secrets/scicat_user
      - SCICAT_PASSWORD_FILE=/run/secrets/scicat_pass
    volumes:
      - type: bind
        source: ${PREFECT_VARS_FILE}
        target: /var/local/vars.toml
      - type: bind
        source: ../backend/prefect/concurrency-limits.toml
        target: /var/local/concurrency-limits.toml
    command: "-v /var/local/vars.toml -s S3_USER_FILE S3_PASSWORD_FILE GITHUB_USER_FILE GITHUB_PASSWORD_FILE SCICAT_USER_FILE SCICAT_PASSWORD_FILE -l /var/local/concurrency-limits.toml"
    depends_on:
      prefect-server:
        condition: service_healthy
    secrets:
      - s3_user
      - s3_password
      - github_user
      - github_pass
      - scicat_user
      - scicat_pass
  prefect-flows-deployment:
    # Uses the runtime image: prefect will import the code and there it needs all packages installed
    image: ${PREFECT_RUNTIME_IMAGE_NAME}:${OPENEM_IMAGE_TAG:-latest}
    build:
      context: ../backend/archiver
      dockerfile: ../prefect/runtime.Dockerfile
      args:
        PREFECT_VERSION: ${PREFECT_VERSION}
        UID: 123
        GID: 123
    networks:
      - internal
    environment:
      ### Prefect specific values
      - PREFECT_LOGGING_LEVEL=${PREFECT_LOGGING_LEVEL}
      - PREFECT_API_URL=http://prefect-server:4200/api
      ### Deployment values for interpolation in prefect.yaml
      - PREFECT_VERSION=${PREFECT_VERSION}
      - PREFECT_ARCHIVER_HOST_SCRATCH=${PREFECT_ARCHIVER_HOST_SCRATCH}
      - ARCHIVER_SCRATCH_FOLDER=${ARCHIVER_SCRATCH_FOLDER}
      - PREFECT_NETWORK=${ENVIRONMENT}_internal
      - PREFECT_RUNTIME_IMAGE=${PREFECT_RUNTIME_IMAGE_NAME}:${OPENEM_IMAGE_TAG:-latest}
    command: prefect --no-prompt deploy --all --prefect-file /prefect.yaml
    working_dir: /app/backend
    volumes:
      - type: bind
        source: ../backend/prefect/prefect.yaml
        target: /prefect.yaml
        read_only: true
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      prefect-server:
        condition: service_healthy
      prefect-config:
        condition: service_completed_successfully
    labels:
      traefik.enable: false
volumes:
  postgres-volume:
    driver: local
  prefect-volume:
    driver: local

secrets:
  postgres_user:
    file: ./.secrets/postgresuser.txt
  postgres_pass:
    file: ./.secrets/postgrespass.txt
  github_user:
    file: ./.secrets/githubuser.txt
  github_pass:
    file: ./.secrets/githubpass.txt
  scicat_user:
    file: ${SCICAT_USER_FILE}
  scicat_pass:
    file: ${SCICAT_PASSWORD_FILE}
  s3_user:
    file: ./.secrets/s3user.txt
  s3_password:
    file: ./.secrets/s3pass.txt
  s3_metrics_token:
    file: ./.secrets/s3_metrics.txt
  idp_client_secret:
    file: ${IDP_CLIENT_SECRET_FILE}
  idp_password:
    file: ${IDP_PASSWORD_FILE}
  job_endpoint_username:
    file: ./.secrets/jobsusername.txt
  job_endpoint_password:
    file: ./.secrets/jobspassword.txt

networks:
  internal:
  dev_traefik_public:
    external: true
  prod_traefik_public:
    external: true
  qa_traefik_public:
    external: true