
[archiver]
ARCHIVER_SCRATCH_FOLDER = "/storage"
ARCHIVER_TARGET_SIZE_GB = 500

[s3]
S3_REGION = "eu-west-1"                        # S3 region
S3_ARCHIVAL_BUCKET = "qa.archival"              # S3 bucket where datasets are retrieved to
S3_LANDINGZONE_BUCKET = "qa.landingzone"          # S3 bucket where datasets are uploaded to  
S3_URL_EXPIRATION_DAYS = 7

[scicat]
SCICAT_ENDPOINT = "https://dacat-qa.psi.ch"
SCICAT_API_PREFIX = "/api/v3" # Route prefix of Scicat instance
SCICAT_DATASETS_API_PREFIX = "/api/v3" # Route prefix of Scicat dataset endpoints
SCICAT_JOBS_API_PREFIX = "/api/v3" # jobs endpoints for jobs endpoints
