name: Deploy Github Pages


on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        run: docker run --rm -v ${PWD}:/docs -it $(docker build -f docs.Dockerfile .) gh-deploy 